#############################################################################
##  v      #                   The Coq Proof Assistant                     ##
## <O___,, #                INRIA - CNRS - LIX - LRI - PPS                 ##
##   \VV/  #                                                               ##
##    //   #  Makefile automagically generated by coq_makefile V8.3        ##
#############################################################################

# WARNING
#
# This Makefile has been automagically generated
# Edit at your own risks !
#
# END OF WARNING

#
# This Makefile was generated by the command line :
# coq_makefile -f Make -o Makefile 
#

# 
# This Makefile may take 3 arguments passed as environment variables:
#   - COQBIN to specify the directory where Coq binaries resides;
#   - CAMLBIN and CAMLP4BIN to give the path for the OCaml and Camlp4/5 binaries.
COQLIB:=$(shell $(COQBIN)coqtop -where | sed -e 's/\\/\\\\/g')
CAMLP4:="$(shell $(COQBIN)coqtop -config | awk -F = '/CAMLP4=/{print $$2}')"
ifndef CAMLP4BIN
  CAMLP4BIN:=$(CAMLBIN)
endif

CAMLP4LIB:=$(shell $(CAMLP4BIN)$(CAMLP4) -where)

##########################
#                        #
# Libraries definitions. #
#                        #
##########################

OCAMLLIBS:=
COQSRCLIBS:=-I $(COQLIB)/kernel -I $(COQLIB)/lib \
  -I $(COQLIB)/library -I $(COQLIB)/parsing \
  -I $(COQLIB)/pretyping -I $(COQLIB)/interp \
  -I $(COQLIB)/proofs -I $(COQLIB)/tactics \
  -I $(COQLIB)/toplevel \
  -I $(COQLIB)/plugins/cc \
  -I $(COQLIB)/plugins/dp \
  -I $(COQLIB)/plugins/extraction \
  -I $(COQLIB)/plugins/field \
  -I $(COQLIB)/plugins/firstorder \
  -I $(COQLIB)/plugins/fourier \
  -I $(COQLIB)/plugins/funind \
  -I $(COQLIB)/plugins/micromega \
  -I $(COQLIB)/plugins/nsatz \
  -I $(COQLIB)/plugins/omega \
  -I $(COQLIB)/plugins/quote \
  -I $(COQLIB)/plugins/ring \
  -I $(COQLIB)/plugins/romega \
  -I $(COQLIB)/plugins/rtauto \
  -I $(COQLIB)/plugins/setoid_ring \
  -I $(COQLIB)/plugins/subtac \
  -I $(COQLIB)/plugins/subtac/test \
  -I $(COQLIB)/plugins/syntax \
  -I $(COQLIB)/plugins/xml
COQLIBS:= -R . MathClasses
COQDOCLIBS:=-R . MathClasses

##########################
#                        #
# Variables definitions. #
#                        #
##########################

ZFLAGS=$(OCAMLLIBS) $(COQSRCLIBS) -I $(CAMLP4LIB)
OPT:=
COQFLAGS:=-q $(OPT) $(COQLIBS) $(OTHERFLAGS) $(COQ_XML)
ifdef CAMLBIN
  COQMKTOPFLAGS:=-camlbin $(CAMLBIN) -camlp4bin $(CAMLP4BIN)
endif
COQC:=$(COQBIN)coqc
COQDEP:=$(COQBIN)coqdep -c
GALLINA:=$(COQBIN)gallina
COQDOC:=$(COQBIN)coqdoc
COQMKTOP:=$(COQBIN)coqmktop
CAMLLIB:=$(shell $(CAMLBIN)ocamlc.opt -where)
CAMLC:=$(CAMLBIN)ocamlc.opt -c -rectypes
CAMLOPTC:=$(CAMLBIN)ocamlopt.opt -c -rectypes
CAMLLINK:=$(CAMLBIN)ocamlc.opt -rectypes
CAMLOPTLINK:=$(CAMLBIN)ocamlopt.opt -rectypes
GRAMMARS:=grammar.cma
CAMLP4EXTEND:=pa_extend.cmo pa_macro.cmo q_MLast.cmo
CAMLP4OPTIONS:=
PP:=-pp "$(CAMLP4BIN)$(CAMLP4)o -I $(CAMLLIB) -I . $(COQSRCLIBS) $(CAMLP4EXTEND) $(GRAMMARS) $(CAMLP4OPTIONS) -impl"

###################################
#                                 #
# Definition of the "all" target. #
#                                 #
###################################

VFILES:=orders/rings.v\
  orders/naturals.v\
  orders/minmax.v\
  orders/orders.v\
  orders/semirings.v\
  orders/maps.v\
  orders/rationals.v\
  orders/fields.v\
  orders/integers.v\
  theory/forget_variety.v\
  theory/cut_minus.v\
  theory/streams.v\
  theory/categories.v\
  theory/abs.v\
  theory/ua_subalgebra.v\
  theory/sequences.v\
  theory/ua_transference.v\
  theory/ua_congruence.v\
  theory/rings.v\
  theory/functors.v\
  theory/monoid_normalization.v\
  theory/ua_homomorphisms.v\
  theory/naturals.v\
  theory/quote_monoid.v\
  theory/monads.v\
  theory/ua_packed.v\
  theory/shiftl.v\
  theory/nat_pow.v\
  theory/ua_products.v\
  theory/ua_subalgebraT.v\
  theory/groups.v\
  theory/ua_mapped_operations.v\
  theory/int_abs.v\
  theory/forget_algebra.v\
  theory/setoids.v\
  theory/rationals.v\
  theory/series.v\
  theory/nat_distance.v\
  theory/jections.v\
  theory/adjunctions.v\
  theory/hom_functor.v\
  theory/ring_ideals.v\
  theory/fields.v\
  theory/int_pow.v\
  theory/ua_term_monad.v\
  theory/integers.v\
  theory/ua_subvariety.v\
  interfaces/vectorspace.v\
  interfaces/sequences.v\
  interfaces/functors.v\
  interfaces/additional_operations.v\
  interfaces/universal_algebra.v\
  interfaces/abstract_algebra.v\
  interfaces/naturals.v\
  interfaces/canonical_names.v\
  interfaces/monads.v\
  interfaces/ua_basic.v\
  interfaces/rationals.v\
  interfaces/integers.v\
  quote/classquote.v\
  implementations/cons_list.v\
  implementations/stdlib_rationals.v\
  implementations/positive_semiring_elements.v\
  implementations/natpair_integers.v\
  implementations/nonneg_semiring_elements.v\
  implementations/stdlib_binary_positives.v\
  implementations/peano_naturals.v\
  implementations/intfrac_rationals.v\
  implementations/field_of_fractions.v\
  implementations/dyadics.v\
  implementations/ZType_integers.v\
  implementations/nonneg_integers_naturals.v\
  implementations/nonzero_field_elements.v\
  implementations/stdlib_binary_naturals.v\
  implementations/polynomials.v\
  implementations/stdlib_binary_integers.v\
  implementations/QType_rationals.v\
  implementations/fast_integers.v\
  implementations/semiring_pairs.v\
  implementations/fast_rationals.v\
  implementations/ne_list.v\
  categories/variety.v\
  categories/JMcat.v\
  categories/setoid.v\
  categories/functor.v\
  categories/unit.v\
  categories/product.v\
  categories/empty.v\
  categories/cat.v\
  categories/dual.v\
  categories/algebra.v\
  varieties/ring.v\
  varieties/open_terms.v\
  varieties/setoid.v\
  varieties/closed_terms.v\
  varieties/semiring.v\
  varieties/semigroup.v\
  varieties/group.v\
  varieties/empty.v\
  varieties/monoid.v\
  misc/benchmarks_nobuild.v\
  misc/setoid_tactics.v\
  misc/util.v\
  misc/JMrelation.v\
  misc/workarounds.v\
  misc/workaround_tactics.v
VOFILES:=$(VFILES:.v=.vo)
GLOBFILES:=$(VFILES:.v=.glob)
VIFILES:=$(VFILES:.v=.vi)
GFILES:=$(VFILES:.v=.g)
HTMLFILES:=$(VFILES:.v=.html)
GHTMLFILES:=$(VFILES:.v=.g.html)

all: $(VOFILES) 
spec: $(VIFILES)

gallina: $(GFILES)

html: $(GLOBFILES) $(VFILES)
	- mkdir -p html
	$(COQDOC) -toc -html $(COQDOCLIBS) -d html $(VFILES)

gallinahtml: $(GLOBFILES) $(VFILES)
	- mkdir -p html
	$(COQDOC) -toc -html -g $(COQDOCLIBS) -d html $(VFILES)

all.ps: $(VFILES)
	$(COQDOC) -toc -ps $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`

all-gal.ps: $(VFILES)
	$(COQDOC) -toc -ps -g $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`

all.pdf: $(VFILES)
	$(COQDOC) -toc -pdf $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`

all-gal.pdf: $(VFILES)
	$(COQDOC) -toc -pdf -g $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`



####################
#                  #
# Special targets. #
#                  #
####################

.PHONY: all opt byte archclean clean install depend html

%.vo %.glob: %.v
	$(COQC) $(COQDEBUG) $(COQFLAGS) $*

%.vi: %.v
	$(COQC) -i $(COQDEBUG) $(COQFLAGS) $*

%.g: %.v
	$(GALLINA) $<

%.tex: %.v
	$(COQDOC) -latex $< -o $@

%.html: %.v %.glob
	$(COQDOC) -html $< -o $@

%.g.tex: %.v
	$(COQDOC) -latex -g $< -o $@

%.g.html: %.v %.glob
	$(COQDOC) -html -g $< -o $@

%.v.d: %.v
	$(COQDEP) -slash $(COQLIBS) "$<" > "$@" || ( RV=$$?; rm -f "$@"; exit $${RV} )

byte:
	$(MAKE) all "OPT:=-byte"

opt:
	$(MAKE) all "OPT:=-opt"

install:
	mkdir -p $(COQLIB)/user-contrib
	(for i in $(VOFILES); do \
	 install -d `dirname $(COQLIB)/user-contrib/MathClasses/$$i`; \
	 install $$i $(COQLIB)/user-contrib/MathClasses/$$i; \
	 done)

clean:
	rm -f $(CMOFILES) $(CMIFILES) $(CMXFILES) $(CMXSFILES) $(OFILES) $(VOFILES) $(VIFILES) $(GFILES) $(MLFILES:.ml=.cmo) $(MLFILES:.ml=.cmx) *~
	rm -f all.ps all-gal.ps all.pdf all-gal.pdf all.glob $(VFILES:.v=.glob) $(HTMLFILES) $(GHTMLFILES) $(VFILES:.v=.tex) $(VFILES:.v=.g.tex) $(VFILES:.v=.v.d)
	- rm -rf html

archclean:
	rm -f *.cmx *.o


printenv: 
	@echo CAMLC =	$(CAMLC)
	@echo CAMLOPTC =	$(CAMLOPTC)
	@echo CAMLP4LIB =	$(CAMLP4LIB)

Makefile: Make
	mv -f Makefile Makefile.bak
	$(COQBIN)coq_makefile -f Make -o Makefile


-include $(VFILES:.v=.v.d)
.SECONDARY: $(VFILES:.v=.v.d)

# WARNING
#
# This Makefile has been automagically generated
# Edit at your own risks !
#
# END OF WARNING

